GET http://localhost:3000/resources

###
GET http://localhost:3000/resources/1

###
POST http://localhost:3000/resources/1
Content-Type: application/json

{

}
###
PATCH http://localhost:3000/resources/1
Content-Type: application/json

{

}
###
DELETE http://localhost:3000/resources/1